# -*- coding: utf-8 -*-
"""Modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kY4WfzyLxtagoUn7TDgfC5xN9Pwegxf9
"""



import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train = pd.read_csv('Titanic_Preprocessing/X_train.csv')
y_train = pd.read_csv('Titanic_Preprocessing/y_train.csv')
X_test = pd.read_csv('Titanic_Preprocessing/X_test.csv')
y_test = pd.read_csv('Titanic_Preprocessing/y_test.csv')

mlflow.autolog()

mlflow.autolog()

with mlflow.start_run():

    model = RandomForestClassifier()

    model.fit(X_train, y_train.values.ravel())
    pred = model.predict(X_test)
    acc = accuracy_score(y_test, pred)

    mlflow.sklearn.log_model(model, "model")

    print("Accuracy:", acc)
